-- AlterTable
ALTER TABLE `order` ADD COLUMN `failedReason` VARCHAR(191) NULL,
    ADD COLUMN `status` ENUM('PLACED', 'PACKED', 'IN_TRANSIT', 'DELIVERED', 'FAILED_IN_TRANSIT', 'FAILED_DELIVERY') NOT NULL DEFAULT 'PLACED';
